# Generated by Django 5.0.2 on 2024-06-16 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadPaquetes', models.BigIntegerField(blank=True, null=True)),
                ('vehiculoSolicitado', models.CharField(blank=True, choices=[('M', 'Moto'), ('C', 'Carro'), ('F', 'Camion')], max_length=1)),
                ('estados', models.CharField(blank=True, choices=[('S', 'Solicitado.'), ('A', 'Agendado, un mensajero tomo tu pedido.'), ('C', 'Tu envío está en camino.'), ('D', 'Tu envío ha llegado a su destino.'), ('E', 'Tu envío ha sido entregado.')], max_length=1)),
                ('descripcion', models.CharField(max_length=300)),
                ('is_complete', models.BooleanField(blank=True, default=False, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('direccion_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion2', to='servicios.direccion')),
                ('direccion_recojer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion1', to='servicios.direccion')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_cliente', to=settings.AUTH_USER_MODEL)),
                ('id_mensajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_mensajero', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
