# Generated by Django 5.0.2 on 2024-05-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='imagenPerfil',
            field=models.ImageField(null=True, upload_to='perfil_imagenes/'),
        ),
        migrations.AddField(
            model_name='mensajero',
            name='placaVehiculo',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
