# Generated by Django 5.0.2 on 2024-06-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cliente_address_cliente_nombresucursal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='customuser',
            name='ciudad',
            field=models.CharField(choices=[('C', 'Santiago de Cali'), ('B', 'Bogota'), ('M', 'Medellin'), ('P', 'Pereira')], default='C', max_length=100),
            preserve_default=False,
        ),
    ]
