# Generated by Django 5.0.2 on 2024-06-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_cliente_address_remove_cliente_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nombres',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
