# Generated by Django 5.0.2 on 2024-06-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_apellidos_customuser_nombres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
